<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <path d="M4.25 20V4L12 14.25L19.75 4V20"
        fill="none"
        stroke="currentColor"
        stroke-width="4.25"
        stroke-linecap="round"
        stroke-linejoin="round"/>
</svg>
