# SPDX-License-Identifier: Apache-2.0

name: Semantic-Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha

jobs:
  semantic-release:
    name: Semantic-Release Action
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
      new-release-version: ${{ steps.release.outputs.new-release-version }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Run Semantic Release
        id: release
        uses: sentenz/actions/semantic-release@13459d04f1c048f60ffc99d50dba5a362111d7b2 # 1.4.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          semantic-version: "25.0.3"
          extra-plugins: |
            @semantic-release/changelog@^6
            @semantic-release/git@^10
            @semantic-release/npm@^13.1.1
            conventional-changelog-conventionalcommits@9.3.1

  sbom:
    name: SBOM
    needs:
      - semantic-release
    if: always() && needs.semantic-release.outputs.new-release-published == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/sbom.yml
    with:
      version: ${{ needs.semantic-release.outputs.new-release-version }}

  vscode-extension:
    name: VS Code Extension
    needs:
      - semantic-release
    if: always() && needs.semantic-release.outputs.new-release-published == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/vscode-extension.yml
    with:
      version: ${{ needs.semantic-release.outputs.new-release-version }}
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
